module.exports = {
  //WORLD_MAX_X: 1000,
  WORLD_MAX_X: 100,
  WORLD_MAX_Y: 100,
  WINDOW_DEFAULT_WIDTH: 100,
  WINDOW_DEFAULT_HEIGHT: 100,
  FISH_COUNT: 20,
  FISH_RESTING_SPEED: 5,
  FISH_STARTLE_SPEED: 50,
  FISH_FOOD_APPROACH_SPEED: 30,
  FISH_FOOD_OVERSHOOT: 40
};
